// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new BuffersinkFlag with the specified value set.
func (f BuffersinkFlag) Add(o BuffersinkFlag) BuffersinkFlag {
	return BuffersinkFlag(uint64(f) | uint64(o))
}

// Del returns a new BuffersinkFlag with the specified value unset.
func (f BuffersinkFlag) Del(o BuffersinkFlag) BuffersinkFlag {
	return BuffersinkFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f BuffersinkFlag) Has(o BuffersinkFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f BuffersinkFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f BuffersinkFlag) Format(s fmt.State, verb rune) {
	var nameMap map[BuffersinkFlag]string
	switch verb {
	case 's':
		nameMap = buffersinkFlagNameMap
	case 'c':
		nameMap = buffersinkFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var buffersinkFlagNameMap = map[BuffersinkFlag]string{
	BuffersinkFlagPeek:      "Peek",
	BuffersinkFlagNoRequest: "NoRequest",
}
var buffersinkFlagCgoNameMap = map[BuffersinkFlag]string{
	BuffersinkFlagPeek:      "AV_BUFFERSINK_FLAG_PEEK",
	BuffersinkFlagNoRequest: "AV_BUFFERSINK_FLAG_NO_REQUEST",
}
