// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new BuffersrcFlag with the specified value set.
func (f BuffersrcFlag) Add(o BuffersrcFlag) BuffersrcFlag {
	return BuffersrcFlag(uint64(f) | uint64(o))
}

// Del returns a new BuffersrcFlag with the specified value unset.
func (f BuffersrcFlag) Del(o BuffersrcFlag) BuffersrcFlag {
	return BuffersrcFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f BuffersrcFlag) Has(o BuffersrcFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f BuffersrcFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f BuffersrcFlag) Format(s fmt.State, verb rune) {
	var nameMap map[BuffersrcFlag]string
	switch verb {
	case 's':
		nameMap = buffersrcFlagNameMap
	case 'c':
		nameMap = buffersrcFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var buffersrcFlagNameMap = map[BuffersrcFlag]string{
	BuffersrcFlagNoCheckFormat: "NoCheckFormat",
	BuffersrcFlagPush:          "Push",
	BuffersrcFlagKeepRef:       "KeepRef",
}
var buffersrcFlagCgoNameMap = map[BuffersrcFlag]string{
	BuffersrcFlagNoCheckFormat: "AV_BUFFERSRC_FLAG_NO_CHECK_FORMAT",
	BuffersrcFlagPush:          "AV_BUFFERSRC_FLAG_PUSH",
	BuffersrcFlagKeepRef:       "AV_BUFFERSRC_FLAG_KEEP_REF",
}
