// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new CodecContextFlag with the specified value set.
func (f CodecContextFlag) Add(o CodecContextFlag) CodecContextFlag {
	return CodecContextFlag(uint64(f) | uint64(o))
}

// Del returns a new CodecContextFlag with the specified value unset.
func (f CodecContextFlag) Del(o CodecContextFlag) CodecContextFlag {
	return CodecContextFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f CodecContextFlag) Has(o CodecContextFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f CodecContextFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f CodecContextFlag) Format(s fmt.State, verb rune) {
	var nameMap map[CodecContextFlag]string
	switch verb {
	case 's':
		nameMap = codecContextFlagNameMap
	case 'c':
		nameMap = codecContextFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var codecContextFlagNameMap = map[CodecContextFlag]string{
	CodecContextFlagUnaligned:     "Unaligned",
	CodecContextFlagQscale:        "Qscale",
	CodecContextFlag4Mv:           "4Mv",
	CodecContextFlagOutputCorrupt: "OutputCorrupt",
	CodecContextFlagQpel:          "Qpel",
	CodecContextFlagPass1:         "Pass1",
	CodecContextFlagPass2:         "Pass2",
	CodecContextFlagLoopFilter:    "LoopFilter",
	CodecContextFlagGray:          "Gray",
	CodecContextFlagPsnr:          "Psnr",
	CodecContextFlagInterlacedDct: "InterlacedDct",
	CodecContextFlagLowDelay:      "LowDelay",
	CodecContextFlagGlobalHeader:  "GlobalHeader",
	CodecContextFlagBitexact:      "Bitexact",
	CodecContextFlagAcPred:        "AcPred",
	CodecContextFlagInterlacedMe:  "InterlacedMe",
	CodecContextFlagClosedGop:     "ClosedGop",
}
var codecContextFlagCgoNameMap = map[CodecContextFlag]string{
	CodecContextFlagUnaligned:     "AV_CODEC_FLAG_UNALIGNED",
	CodecContextFlagQscale:        "AV_CODEC_FLAG_QSCALE",
	CodecContextFlag4Mv:           "AV_CODEC_FLAG_4MV",
	CodecContextFlagOutputCorrupt: "AV_CODEC_FLAG_OUTPUT_CORRUPT",
	CodecContextFlagQpel:          "AV_CODEC_FLAG_QPEL",
	CodecContextFlagPass1:         "AV_CODEC_FLAG_PASS1",
	CodecContextFlagPass2:         "AV_CODEC_FLAG_PASS2",
	CodecContextFlagLoopFilter:    "AV_CODEC_FLAG_LOOP_FILTER",
	CodecContextFlagGray:          "AV_CODEC_FLAG_GRAY",
	CodecContextFlagPsnr:          "AV_CODEC_FLAG_PSNR",
	CodecContextFlagInterlacedDct: "AV_CODEC_FLAG_INTERLACED_DCT",
	CodecContextFlagLowDelay:      "AV_CODEC_FLAG_LOW_DELAY",
	CodecContextFlagGlobalHeader:  "AV_CODEC_FLAG_GLOBAL_HEADER",
	CodecContextFlagBitexact:      "AV_CODEC_FLAG_BITEXACT",
	CodecContextFlagAcPred:        "AV_CODEC_FLAG_AC_PRED",
	CodecContextFlagInterlacedMe:  "AV_CODEC_FLAG_INTERLACED_ME",
	CodecContextFlagClosedGop:     "AV_CODEC_FLAG_CLOSED_GOP",
}

// Del returns a new CodecContextFlag2 with the specified value set.
func (f CodecContextFlag2) Add(o CodecContextFlag2) CodecContextFlag2 {
	return CodecContextFlag2(uint64(f) | uint64(o))
}

// Del returns a new CodecContextFlag2 with the specified value unset.
func (f CodecContextFlag2) Del(o CodecContextFlag2) CodecContextFlag2 {
	return CodecContextFlag2(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f CodecContextFlag2) Has(o CodecContextFlag2) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f CodecContextFlag2) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f CodecContextFlag2) Format(s fmt.State, verb rune) {
	var nameMap map[CodecContextFlag2]string
	switch verb {
	case 's':
		nameMap = codecContextFlag2NameMap
	case 'c':
		nameMap = codecContextFlag2CgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var codecContextFlag2NameMap = map[CodecContextFlag2]string{
	CodecFlag2Fast:        "CodecFlag2Fast",
	CodecFlag2NoOutput:    "CodecFlag2NoOutput",
	CodecFlag2LocalHeader: "CodecFlag2LocalHeader",
	CodecFlag2Chunks:      "CodecFlag2Chunks",
	CodecFlag2IgnoreCrop:  "CodecFlag2IgnoreCrop",
	CodecFlag2ShowAll:     "CodecFlag2ShowAll",
	CodecFlag2ExportMvs:   "CodecFlag2ExportMvs",
	CodecFlag2SkipManual:  "CodecFlag2SkipManual",
	CodecFlag2RoFlushNoop: "CodecFlag2RoFlushNoop",
	CodecFlag2IccProfiles: "CodecFlag2IccProfiles",
}
var codecContextFlag2CgoNameMap = map[CodecContextFlag2]string{
	CodecFlag2Fast:        "AV_CODEC_FLAG2_FAST",
	CodecFlag2NoOutput:    "AV_CODEC_FLAG2_NO_OUTPUT",
	CodecFlag2LocalHeader: "AV_CODEC_FLAG2_LOCAL_HEADER",
	CodecFlag2Chunks:      "AV_CODEC_FLAG2_CHUNKS",
	CodecFlag2IgnoreCrop:  "AV_CODEC_FLAG2_IGNORE_CROP",
	CodecFlag2ShowAll:     "AV_CODEC_FLAG2_SHOW_ALL",
	CodecFlag2ExportMvs:   "AV_CODEC_FLAG2_EXPORT_MVS",
	CodecFlag2SkipManual:  "AV_CODEC_FLAG2_SKIP_MANUAL",
	CodecFlag2RoFlushNoop: "AV_CODEC_FLAG2_RO_FLUSH_NOOP",
	CodecFlag2IccProfiles: "AV_CODEC_FLAG2_ICC_PROFILES",
}
