// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new CodecHardwareConfigMethodFlag with the specified value set.
func (f CodecHardwareConfigMethodFlag) Add(o CodecHardwareConfigMethodFlag) CodecHardwareConfigMethodFlag {
	return CodecHardwareConfigMethodFlag(uint64(f) | uint64(o))
}

// Del returns a new CodecHardwareConfigMethodFlag with the specified value unset.
func (f CodecHardwareConfigMethodFlag) Del(o CodecHardwareConfigMethodFlag) CodecHardwareConfigMethodFlag {
	return CodecHardwareConfigMethodFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f CodecHardwareConfigMethodFlag) Has(o CodecHardwareConfigMethodFlag) bool {
	return uint64(f)&uint64(o) > 0
}

// IsSingleFlag returns true if the value represents single flag value.
func (f CodecHardwareConfigMethodFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f CodecHardwareConfigMethodFlag) Format(s fmt.State, verb rune) {
	var nameMap map[CodecHardwareConfigMethodFlag]string
	switch verb {
	case 's':
		nameMap = codecHardwareConfigMethodFlagNameMap
	case 'c':
		nameMap = codecHardwareConfigMethodFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var codecHardwareConfigMethodFlagNameMap = map[CodecHardwareConfigMethodFlag]string{
	CodecHardwareConfigMethodFlagAdHoc:       "AdHoc",
	CodecHardwareConfigMethodFlagHwDeviceCtx: "HwDeviceCtx",
	CodecHardwareConfigMethodFlagHwFramesCtx: "HwFramesCtx",
	CodecHardwareConfigMethodFlagInternal:    "Internal",
}
var codecHardwareConfigMethodFlagCgoNameMap = map[CodecHardwareConfigMethodFlag]string{
	CodecHardwareConfigMethodFlagAdHoc:       "AV_CODEC_HW_CONFIG_METHOD_AD_HOC",
	CodecHardwareConfigMethodFlagHwDeviceCtx: "AV_CODEC_HW_CONFIG_METHOD_HW_DEVICE_CTX",
	CodecHardwareConfigMethodFlagHwFramesCtx: "AV_CODEC_HW_CONFIG_METHOD_HW_FRAMES_CTX",
	CodecHardwareConfigMethodFlagInternal:    "AV_CODEC_HW_CONFIG_METHOD_INTERNAL",
}
