// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new DictionaryFlag with the specified value set.
func (f DictionaryFlag) Add(o DictionaryFlag) DictionaryFlag {
	return DictionaryFlag(uint64(f) | uint64(o))
}

// Del returns a new DictionaryFlag with the specified value unset.
func (f DictionaryFlag) Del(o DictionaryFlag) DictionaryFlag {
	return DictionaryFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f DictionaryFlag) Has(o DictionaryFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f DictionaryFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f DictionaryFlag) Format(s fmt.State, verb rune) {
	var nameMap map[DictionaryFlag]string
	switch verb {
	case 's':
		nameMap = dictionaryFlagNameMap
	case 'c':
		nameMap = dictionaryFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var dictionaryFlagNameMap = map[DictionaryFlag]string{
	DictionaryFlagMatchCase:     "MatchCase",
	DictionaryFlagIgnoreSuffix:  "IgnoreSuffix",
	DictionaryFlagDontStrdupKey: "DontStrdupKey",
	DictionaryFlagDontStrdupVal: "DontStrdupVal",
	DictionaryFlagDontOverwrite: "DontOverwrite",
	DictionaryFlagAppend:        "Append",
	DictionaryFlagMultikey:      "Multikey",
}
var dictionaryFlagCgoNameMap = map[DictionaryFlag]string{
	DictionaryFlagMatchCase:     "AV_DICT_MATCH_CASE",
	DictionaryFlagIgnoreSuffix:  "AV_DICT_IGNORE_SUFFIX",
	DictionaryFlagDontStrdupKey: "AV_DICT_DONT_STRDUP_KEY",
	DictionaryFlagDontStrdupVal: "AV_DICT_DONT_STRDUP_VAL",
	DictionaryFlagDontOverwrite: "AV_DICT_DONT_OVERWRITE",
	DictionaryFlagAppend:        "AV_DICT_APPEND",
	DictionaryFlagMultikey:      "AV_DICT_MULTIKEY",
}
