// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new DispositionFlag with the specified value set.
func (f DispositionFlag) Add(o DispositionFlag) DispositionFlag {
	return DispositionFlag(uint64(f) | uint64(o))
}

// Del returns a new DispositionFlag with the specified value unset.
func (f DispositionFlag) Del(o DispositionFlag) DispositionFlag {
	return DispositionFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f DispositionFlag) Has(o DispositionFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f DispositionFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f DispositionFlag) Format(s fmt.State, verb rune) {
	var nameMap map[DispositionFlag]string
	switch verb {
	case 's':
		nameMap = dispositionFlagNameMap
	case 'c':
		nameMap = dispositionFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var dispositionFlagNameMap = map[DispositionFlag]string{
	DispositionFlagDefault:         "Default",
	DispositionFlagDub:             "Dub",
	DispositionFlagOriginal:        "Original",
	DispositionFlagComment:         "Comment",
	DispositionFlagLyrics:          "Lyrics",
	DispositionFlagKaraoke:         "Karaoke",
	DispositionFlagForced:          "Forced",
	DispositionFlagHearingImpaired: "HearingImpaired",
	DispositionFlagVisualImpaired:  "VisualImpaired",
	DispositionFlagCleanEffects:    "CleanEffects",
	DispositionFlagAttachedPic:     "AttachedPic",
	DispositionFlagTimedThumbnails: "TimedThumbnails",
	DispositionFlagNonDiegetic:     "NonDiegetic",
	DispositionFlagCaptions:        "Captions",
	DispositionFlagDescriptions:    "Descriptions",
	DispositionFlagMetadata:        "Metadata",
	DispositionFlagDependent:       "Dependent",
	DispositionFlagStillImage:      "StillImage",
}
var dispositionFlagCgoNameMap = map[DispositionFlag]string{
	DispositionFlagDefault:         "AV_DISPOSITION_DEFAULT",
	DispositionFlagDub:             "AV_DISPOSITION_DUB",
	DispositionFlagOriginal:        "AV_DISPOSITION_ORIGINAL",
	DispositionFlagComment:         "AV_DISPOSITION_COMMENT",
	DispositionFlagLyrics:          "AV_DISPOSITION_LYRICS",
	DispositionFlagKaraoke:         "AV_DISPOSITION_KARAOKE",
	DispositionFlagForced:          "AV_DISPOSITION_FORCED",
	DispositionFlagHearingImpaired: "AV_DISPOSITION_HEARING_IMPAIRED",
	DispositionFlagVisualImpaired:  "AV_DISPOSITION_VISUAL_IMPAIRED",
	DispositionFlagCleanEffects:    "AV_DISPOSITION_CLEAN_EFFECTS",
	DispositionFlagAttachedPic:     "AV_DISPOSITION_ATTACHED_PIC",
	DispositionFlagTimedThumbnails: "AV_DISPOSITION_TIMED_THUMBNAILS",
	DispositionFlagNonDiegetic:     "AV_DISPOSITION_NON_DIEGETIC",
	DispositionFlagCaptions:        "AV_DISPOSITION_CAPTIONS",
	DispositionFlagDescriptions:    "AV_DISPOSITION_DESCRIPTIONS",
	DispositionFlagMetadata:        "AV_DISPOSITION_METADATA",
	DispositionFlagDependent:       "AV_DISPOSITION_DEPENDENT",
	DispositionFlagStillImage:      "AV_DISPOSITION_STILL_IMAGE",
}
