// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new ErrorRecognitionFlag with the specified value set.
func (f ErrorRecognitionFlag) Add(o ErrorRecognitionFlag) ErrorRecognitionFlag {
	return ErrorRecognitionFlag(uint64(f) | uint64(o))
}

// Del returns a new ErrorRecognitionFlag with the specified value unset.
func (f ErrorRecognitionFlag) Del(o ErrorRecognitionFlag) ErrorRecognitionFlag {
	return ErrorRecognitionFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f ErrorRecognitionFlag) Has(o ErrorRecognitionFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f ErrorRecognitionFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f ErrorRecognitionFlag) Format(s fmt.State, verb rune) {
	var nameMap map[ErrorRecognitionFlag]string
	switch verb {
	case 's':
		nameMap = errorRecognitionFlagNameMap
	case 'c':
		nameMap = errorRecognitionFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var errorRecognitionFlagNameMap = map[ErrorRecognitionFlag]string{
	ErrorRecognitionFlagAggressive: "Aggressive",
	ErrorRecognitionFlagBitstream:  "Bitstream",
	ErrorRecognitionFlagBuffer:     "Buffer",
	ErrorRecognitionFlagCareful:    "Careful",
	ErrorRecognitionFlagCompliant:  "Compliant",
	ErrorRecognitionFlagCRCCheck:   "CRCCheck",
	ErrorRecognitionFlagExplode:    "Explode",
	ErrorRecognitionFlagIgnoreErr:  "IgnoreErr",
}
var errorRecognitionFlagCgoNameMap = map[ErrorRecognitionFlag]string{
	ErrorRecognitionFlagAggressive: "AV_EF_AGGRESSIVE",
	ErrorRecognitionFlagBitstream:  "AV_EF_BITSTREAM",
	ErrorRecognitionFlagBuffer:     "AV_EF_BUFFER",
	ErrorRecognitionFlagCareful:    "AV_EF_CAREFUL",
	ErrorRecognitionFlagCompliant:  "AV_EF_COMPLIANT",
	ErrorRecognitionFlagCRCCheck:   "AV_EF_CRCCHECK",
	ErrorRecognitionFlagExplode:    "AV_EF_EXPLODE",
	ErrorRecognitionFlagIgnoreErr:  "AV_EF_IGNORE_ERR",
}
