// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new FilterCommandFlag with the specified value set.
func (f FilterCommandFlag) Add(o FilterCommandFlag) FilterCommandFlag {
	return FilterCommandFlag(uint64(f) | uint64(o))
}

// Del returns a new FilterCommandFlag with the specified value unset.
func (f FilterCommandFlag) Del(o FilterCommandFlag) FilterCommandFlag {
	return FilterCommandFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f FilterCommandFlag) Has(o FilterCommandFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f FilterCommandFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f FilterCommandFlag) Format(s fmt.State, verb rune) {
	var nameMap map[FilterCommandFlag]string
	switch verb {
	case 's':
		nameMap = filterCommandFlagNameMap
	case 'c':
		nameMap = filterCommandFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var filterCommandFlagNameMap = map[FilterCommandFlag]string{
	FilterCommandFlagOne:  "One",
	FilterCommandFlagFast: "Fast",
}
var filterCommandFlagCgoNameMap = map[FilterCommandFlag]string{
	FilterCommandFlagOne:  "AVFILTER_CMD_FLAG_ONE",
	FilterCommandFlagFast: "AVFILTER_CMD_FLAG_FAST",
}
