// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new FilterFlag with the specified value set.
func (f FilterFlag) Add(o FilterFlag) FilterFlag { return FilterFlag(uint64(f) | uint64(o)) }

// Del returns a new FilterFlag with the specified value unset.
func (f FilterFlag) Del(o FilterFlag) FilterFlag { return FilterFlag(uint64(f) &^ uint64(o)) }

// Has returns true if value has the specific value set.
func (f FilterFlag) Has(o FilterFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f FilterFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f FilterFlag) Format(s fmt.State, verb rune) {
	var nameMap map[FilterFlag]string
	switch verb {
	case 's':
		nameMap = filterFlagNameMap
	case 'c':
		nameMap = filterFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var filterFlagNameMap = map[FilterFlag]string{
	FilterFlagDynamicInputs:           "DynamicInputs",
	FilterFlagDynamicOutputs:          "DynamicOutputs",
	FilterFlagSliceThreads:            "SliceThreads",
	FilterFlagMetadataOnly:            "MetadataOnly",
	FilterFlagHardwareDevice:          "HardwareDevice",
	FilterFlagSupportTimelineGeneric:  "SupportTimelineGeneric",
	FilterFlagSupportTimelineInternal: "SupportTimelineInternal",
	FilterFlagSupportTimeline:         "SupportTimeline",
}
var filterFlagCgoNameMap = map[FilterFlag]string{
	FilterFlagDynamicInputs:           "AVFILTER_FLAG_DYNAMIC_INPUTS",
	FilterFlagDynamicOutputs:          "AVFILTER_FLAG_DYNAMIC_OUTPUTS",
	FilterFlagSliceThreads:            "AVFILTER_FLAG_SLICE_THREADS",
	FilterFlagMetadataOnly:            "AVFILTER_FLAG_METADATA_ONLY",
	FilterFlagHardwareDevice:          "AVFILTER_FLAG_HWDEVICE",
	FilterFlagSupportTimelineGeneric:  "AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC",
	FilterFlagSupportTimelineInternal: "AVFILTER_FLAG_SUPPORT_TIMELINE_INTERNAL",
	FilterFlagSupportTimeline:         "AVFILTER_FLAG_SUPPORT_TIMELINE",
}
