// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new FormatEventFlag with the specified value set.
func (f FormatEventFlag) Add(o FormatEventFlag) FormatEventFlag {
	return FormatEventFlag(uint64(f) | uint64(o))
}

// Del returns a new FormatEventFlag with the specified value unset.
func (f FormatEventFlag) Del(o FormatEventFlag) FormatEventFlag {
	return FormatEventFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f FormatEventFlag) Has(o FormatEventFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f FormatEventFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f FormatEventFlag) Format(s fmt.State, verb rune) {
	var nameMap map[FormatEventFlag]string
	switch verb {
	case 's':
		nameMap = formatEventFlagNameMap
	case 'c':
		nameMap = formatEventFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var formatEventFlagNameMap = map[FormatEventFlag]string{
	FormatEventFlagMetadataUpdated: "MetadataUpdated",
}
var formatEventFlagCgoNameMap = map[FormatEventFlag]string{
	FormatEventFlagMetadataUpdated: "AVFMT_EVENT_FLAG_METADATA_UPDATED",
}
