// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new FormatContextCtxFlag with the specified value set.
func (f FormatContextCtxFlag) Add(o FormatContextCtxFlag) FormatContextCtxFlag {
	return FormatContextCtxFlag(uint64(f) | uint64(o))
}

// Del returns a new FormatContextCtxFlag with the specified value unset.
func (f FormatContextCtxFlag) Del(o FormatContextCtxFlag) FormatContextCtxFlag {
	return FormatContextCtxFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f FormatContextCtxFlag) Has(o FormatContextCtxFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f FormatContextCtxFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f FormatContextCtxFlag) Format(s fmt.State, verb rune) {
	var nameMap map[FormatContextCtxFlag]string
	switch verb {
	case 's':
		nameMap = formatContextCtxFlagNameMap
	case 'c':
		nameMap = formatContextCtxFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var formatContextCtxFlagNameMap = map[FormatContextCtxFlag]string{
	FormatContextCtxFlagNoHeader:   "NoHeader",
	FormatContextCtxFlagUnseekable: "Unseekable",
}
var formatContextCtxFlagCgoNameMap = map[FormatContextCtxFlag]string{
	FormatContextCtxFlagNoHeader:   "AVFMTCTX_NOHEADER",
	FormatContextCtxFlagUnseekable: "AVFMTCTX_UNSEEKABLE",
}
