// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new FormatContextFlag with the specified value set.
func (f FormatContextFlag) Add(o FormatContextFlag) FormatContextFlag {
	return FormatContextFlag(uint64(f) | uint64(o))
}

// Del returns a new FormatContextFlag with the specified value unset.
func (f FormatContextFlag) Del(o FormatContextFlag) FormatContextFlag {
	return FormatContextFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f FormatContextFlag) Has(o FormatContextFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f FormatContextFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f FormatContextFlag) Format(s fmt.State, verb rune) {
	var nameMap map[FormatContextFlag]string
	switch verb {
	case 's':
		nameMap = formatContextFlagNameMap
	case 'c':
		nameMap = formatContextFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var formatContextFlagNameMap = map[FormatContextFlag]string{
	FormatContextFlagGenPts:         "GenPts",
	FormatContextFlagIgnidx:         "Ignidx",
	FormatContextFlagNonblock:       "Nonblock",
	FormatContextFlagIgnDts:         "IgnDts",
	FormatContextFlagNofillin:       "Nofillin",
	FormatContextFlagNoparse:        "Noparse",
	FormatContextFlagNobuffer:       "Nobuffer",
	FormatContextFlagCustomIo:       "CustomIo",
	FormatContextFlagDiscardCorrupt: "DiscardCorrupt",
	FormatContextFlagFlushPackets:   "FlushPackets",
	FormatContextFlagBitexact:       "Bitexact",
	FormatContextFlagSortDts:        "SortDts",
	FormatContextFlagFastSeek:       "FastSeek",
	FormatContextFlagShortest:       "Shortest",
	FormatContextFlagAutoBsf:        "AutoBsf",
}
var formatContextFlagCgoNameMap = map[FormatContextFlag]string{
	FormatContextFlagGenPts:         "AVFMT_FLAG_GENPTS",
	FormatContextFlagIgnidx:         "AVFMT_FLAG_IGNIDX",
	FormatContextFlagNonblock:       "AVFMT_FLAG_NONBLOCK",
	FormatContextFlagIgnDts:         "AVFMT_FLAG_IGNDTS",
	FormatContextFlagNofillin:       "AVFMT_FLAG_NOFILLIN",
	FormatContextFlagNoparse:        "AVFMT_FLAG_NOPARSE",
	FormatContextFlagNobuffer:       "AVFMT_FLAG_NOBUFFER",
	FormatContextFlagCustomIo:       "AVFMT_FLAG_CUSTOM_IO",
	FormatContextFlagDiscardCorrupt: "AVFMT_FLAG_DISCARD_CORRUPT",
	FormatContextFlagFlushPackets:   "AVFMT_FLAG_FLUSH_PACKETS",
	FormatContextFlagBitexact:       "AVFMT_FLAG_BITEXACT",
	FormatContextFlagSortDts:        "AVFMT_FLAG_SORT_DTS",
	FormatContextFlagFastSeek:       "AVFMT_FLAG_FAST_SEEK",
	FormatContextFlagShortest:       "AVFMT_FLAG_SHORTEST",
	FormatContextFlagAutoBsf:        "AVFMT_FLAG_AUTO_BSF",
}
