// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new IOContextFlag with the specified value set.
func (f IOContextFlag) Add(o IOContextFlag) IOContextFlag {
	return IOContextFlag(uint64(f) | uint64(o))
}

// Del returns a new IOContextFlag with the specified value unset.
func (f IOContextFlag) Del(o IOContextFlag) IOContextFlag {
	return IOContextFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f IOContextFlag) Has(o IOContextFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f IOContextFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f IOContextFlag) Format(s fmt.State, verb rune) {
	var nameMap map[IOContextFlag]string
	switch verb {
	case 's':
		nameMap = iOContextFlagNameMap
	case 'c':
		nameMap = iOContextFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var iOContextFlagNameMap = map[IOContextFlag]string{
	IOContextFlagRead:      "Read",
	IOContextFlagWrite:     "Write",
	IOContextFlagReadWrite: "ReadWrite",
	IOContextFlagNonBlock:  "NonBlock",
	IOContextFlagDirect:    "Direct",
}
var iOContextFlagCgoNameMap = map[IOContextFlag]string{
	IOContextFlagRead:      "AVIO_FLAG_READ",
	IOContextFlagWrite:     "AVIO_FLAG_WRITE",
	IOContextFlagReadWrite: "AVIO_FLAG_READ_WRITE",
	IOContextFlagNonBlock:  "AVIO_FLAG_NONBLOCK",
	IOContextFlagDirect:    "AVIO_FLAG_DIRECT",
}
