// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new IOFormatFlag with the specified value set.
func (f IOFormatFlag) Add(o IOFormatFlag) IOFormatFlag { return IOFormatFlag(uint64(f) | uint64(o)) }

// Del returns a new IOFormatFlag with the specified value unset.
func (f IOFormatFlag) Del(o IOFormatFlag) IOFormatFlag { return IOFormatFlag(uint64(f) &^ uint64(o)) }

// Has returns true if value has the specific value set.
func (f IOFormatFlag) Has(o IOFormatFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f IOFormatFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f IOFormatFlag) Format(s fmt.State, verb rune) {
	var nameMap map[IOFormatFlag]string
	switch verb {
	case 's':
		nameMap = iOFormatFlagNameMap
	case 'c':
		nameMap = iOFormatFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var iOFormatFlagNameMap = map[IOFormatFlag]string{
	IOFormatFlagNofile:       "Nofile",
	IOFormatFlagNeednumber:   "Neednumber",
	IOFormatFlagShowIds:      "ShowIds",
	IOFormatFlagGlobalheader: "Globalheader",
	IOFormatFlagNotimestamps: "Notimestamps",
	IOFormatFlagGenericIndex: "GenericIndex",
	IOFormatFlagTsDiscont:    "TsDiscont",
	IOFormatFlagVariableFps:  "VariableFps",
	IOFormatFlagNodimensions: "Nodimensions",
	IOFormatFlagNostreams:    "Nostreams",
	IOFormatFlagNobinsearch:  "Nobinsearch",
	IOFormatFlagNogensearch:  "Nogensearch",
	IOFormatFlagNoByteSeek:   "NoByteSeek",
	IOFormatFlagAllowFlush:   "AllowFlush",
	IOFormatFlagTsNonstrict:  "TsNonstrict",
	IOFormatFlagTsNegative:   "TsNegative",
	IOFormatFlagSeekToPts:    "SeekToPts",
}
var iOFormatFlagCgoNameMap = map[IOFormatFlag]string{
	IOFormatFlagNofile:       "AVFMT_NOFILE",
	IOFormatFlagNeednumber:   "AVFMT_NEEDNUMBER",
	IOFormatFlagShowIds:      "AVFMT_SHOW_IDS",
	IOFormatFlagGlobalheader: "AVFMT_GLOBALHEADER",
	IOFormatFlagNotimestamps: "AVFMT_NOTIMESTAMPS",
	IOFormatFlagGenericIndex: "AVFMT_GENERIC_INDEX",
	IOFormatFlagTsDiscont:    "AVFMT_TS_DISCONT",
	IOFormatFlagVariableFps:  "AVFMT_VARIABLE_FPS",
	IOFormatFlagNodimensions: "AVFMT_NODIMENSIONS",
	IOFormatFlagNostreams:    "AVFMT_NOSTREAMS",
	IOFormatFlagNobinsearch:  "AVFMT_NOBINSEARCH",
	IOFormatFlagNogensearch:  "AVFMT_NOGENSEARCH",
	IOFormatFlagNoByteSeek:   "AVFMT_NO_BYTE_SEEK",
	IOFormatFlagAllowFlush:   "AVFMT_ALLOW_FLUSH",
	IOFormatFlagTsNonstrict:  "AVFMT_TS_NONSTRICT",
	IOFormatFlagTsNegative:   "AVFMT_TS_NEGATIVE",
	IOFormatFlagSeekToPts:    "AVFMT_SEEK_TO_PTS",
}
