// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new OptionSearchFlag with the specified value set.
func (f OptionSearchFlag) Add(o OptionSearchFlag) OptionSearchFlag {
	return OptionSearchFlag(uint64(f) | uint64(o))
}

// Del returns a new OptionSearchFlag with the specified value unset.
func (f OptionSearchFlag) Del(o OptionSearchFlag) OptionSearchFlag {
	return OptionSearchFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f OptionSearchFlag) Has(o OptionSearchFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f OptionSearchFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f OptionSearchFlag) Format(s fmt.State, verb rune) {
	var nameMap map[OptionSearchFlag]string
	switch verb {
	case 's':
		nameMap = optionSearchFlagNameMap
	case 'c':
		nameMap = optionSearchFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var optionSearchFlagNameMap = map[OptionSearchFlag]string{
	OptionSearchFlagChildren:   "Children",
	OptionSearchFlagFakeObject: "FakeObject",
}
var optionSearchFlagCgoNameMap = map[OptionSearchFlag]string{
	OptionSearchFlagChildren:   "AV_OPT_SEARCH_CHILDREN",
	OptionSearchFlagFakeObject: "AV_OPT_SEARCH_FAKE_OBJ",
}
