// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

func (f OptionType) Format(s fmt.State, verb rune) {
	var nameMap map[OptionType]string
	switch verb {
	case 's':
		nameMap = optionTypeNameMap
	case 'c':
		nameMap = optionTypeCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	fmt.Fprint(s, nameMap[f])
	if s.Flag('+') {
		fmt.Fprintf(s, "(%d)", int64(f))
	}
}

var optionTypeNameMap = map[OptionType]string{
	OptionTypeString:    "String",
	OptionTypeBool:      "Bool",
	OptionTypeInt:       "Int",
	OptionTypeInt64:     "Int64",
	OptionTypeUint64:    "Uint64",
	OptionTypeDouble:    "Double",
	OptionTypeFloat:     "Float",
	OptionTypeRational:  "Rational",
	OptionTypeVideoRate: "VideoRate",
	OptionTypeBinary:    "Binary",
	OptionTypeImageSize: "ImageSize",
	OptionTypeConst:     "Const",
	OptionTypeDict:      "Dict",
	OptionTypePixelFmt:  "PixelFmt",
	OptionTypeSampleFmt: "SampleFmt",
	OptionTypeDuration:  "Duration",
	OptionTypeColor:     "Color",
	OptionTypeChlayout:  "Chlayout",
	OptionTypeFlags:     "Flags",
	OptionTypeFlagArray: "FlagArray",
}
var optionTypeCgoNameMap = map[OptionType]string{
	OptionTypeString:    "AV_OPT_TYPE_STRING",
	OptionTypeBool:      "AV_OPT_TYPE_BOOL",
	OptionTypeInt:       "AV_OPT_TYPE_INT",
	OptionTypeInt64:     "AV_OPT_TYPE_INT64",
	OptionTypeUint64:    "AV_OPT_TYPE_UINT64",
	OptionTypeDouble:    "AV_OPT_TYPE_DOUBLE",
	OptionTypeFloat:     "AV_OPT_TYPE_FLOAT",
	OptionTypeRational:  "AV_OPT_TYPE_RATIONAL",
	OptionTypeVideoRate: "AV_OPT_TYPE_VIDEO_RATE",
	OptionTypeBinary:    "AV_OPT_TYPE_BINARY",
	OptionTypeImageSize: "AV_OPT_TYPE_IMAGE_SIZE",
	OptionTypeConst:     "AV_OPT_TYPE_CONST",
	OptionTypeDict:      "AV_OPT_TYPE_DICT",
	OptionTypePixelFmt:  "AV_OPT_TYPE_PIXEL_FMT",
	OptionTypeSampleFmt: "AV_OPT_TYPE_SAMPLE_FMT",
	OptionTypeDuration:  "AV_OPT_TYPE_DURATION",
	OptionTypeColor:     "AV_OPT_TYPE_COLOR",
	OptionTypeChlayout:  "AV_OPT_TYPE_CHLAYOUT",
	OptionTypeFlags:     "AV_OPT_TYPE_FLAGS",
	OptionTypeFlagArray: "AV_OPT_TYPE_FLAG_ARRAY",
}

// Del returns a new OptionFlag with the specified value set.
func (f OptionFlag) Add(o OptionFlag) OptionFlag { return OptionFlag(uint64(f) | uint64(o)) }

// Del returns a new OptionFlag with the specified value unset.
func (f OptionFlag) Del(o OptionFlag) OptionFlag { return OptionFlag(uint64(f) &^ uint64(o)) }

// Has returns true if value has the specific value set.
func (f OptionFlag) Has(o OptionFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f OptionFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f OptionFlag) Format(s fmt.State, verb rune) {
	var nameMap map[OptionFlag]string
	switch verb {
	case 's':
		nameMap = optionFlagNameMap
	case 'c':
		nameMap = optionFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var optionFlagNameMap = map[OptionFlag]string{
	OptionFlagEncodingParam:  "EncodingParam",
	OptionFlagDecodingParam:  "DecodingParam",
	OptionFlagAudioParam:     "AudioParam",
	OptionFlagVideoParam:     "VideoParam",
	OptionFlagSubtitleParam:  "SubtitleParam",
	OptionFlagExport:         "Export",
	OptionFlagReadonly:       "Readonly",
	OptionFlagBsfParam:       "BsfParam",
	OptionFlagRuntimeParam:   "RuntimeParam",
	OptionFlagFilteringParam: "FilteringParam",
	OptionFlagDeprecated:     "Deprecated",
	OptionFlagChildConsts:    "ChildConsts",
}
var optionFlagCgoNameMap = map[OptionFlag]string{
	OptionFlagEncodingParam:  "AV_OPT_FLAG_ENCODING_PARAM",
	OptionFlagDecodingParam:  "AV_OPT_FLAG_DECODING_PARAM",
	OptionFlagAudioParam:     "AV_OPT_FLAG_AUDIO_PARAM",
	OptionFlagVideoParam:     "AV_OPT_FLAG_VIDEO_PARAM",
	OptionFlagSubtitleParam:  "AV_OPT_FLAG_SUBTITLE_PARAM",
	OptionFlagExport:         "AV_OPT_FLAG_EXPORT",
	OptionFlagReadonly:       "AV_OPT_FLAG_READONLY",
	OptionFlagBsfParam:       "AV_OPT_FLAG_BSF_PARAM",
	OptionFlagRuntimeParam:   "AV_OPT_FLAG_RUNTIME_PARAM",
	OptionFlagFilteringParam: "AV_OPT_FLAG_FILTERING_PARAM",
	OptionFlagDeprecated:     "AV_OPT_FLAG_DEPRECATED",
	OptionFlagChildConsts:    "AV_OPT_FLAG_CHILD_CONSTS",
}
