// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new PacketFlag with the specified value set.
func (f PacketFlag) Add(o PacketFlag) PacketFlag { return PacketFlag(uint64(f) | uint64(o)) }

// Del returns a new PacketFlag with the specified value unset.
func (f PacketFlag) Del(o PacketFlag) PacketFlag { return PacketFlag(uint64(f) &^ uint64(o)) }

// Has returns true if value has the specific value set.
func (f PacketFlag) Has(o PacketFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f PacketFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f PacketFlag) Format(s fmt.State, verb rune) {
	var nameMap map[PacketFlag]string
	switch verb {
	case 's':
		nameMap = packetFlagNameMap
	case 'c':
		nameMap = packetFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var packetFlagNameMap = map[PacketFlag]string{
	PacketFlagCorrupt: "Corrupt",
	PacketFlagDiscard: "Discard",
	PacketFlagKey:     "Key",
}
var packetFlagCgoNameMap = map[PacketFlag]string{
	PacketFlagCorrupt: "AV_PKT_FLAG_CORRUPT",
	PacketFlagDiscard: "AV_PKT_FLAG_DISCARD",
	PacketFlagKey:     "AV_PKT_FLAG_KEY",
}
