// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new PixelFormatDescriptorFlag with the specified value set.
func (f PixelFormatDescriptorFlag) Add(o PixelFormatDescriptorFlag) PixelFormatDescriptorFlag {
	return PixelFormatDescriptorFlag(uint64(f) | uint64(o))
}

// Del returns a new PixelFormatDescriptorFlag with the specified value unset.
func (f PixelFormatDescriptorFlag) Del(o PixelFormatDescriptorFlag) PixelFormatDescriptorFlag {
	return PixelFormatDescriptorFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f PixelFormatDescriptorFlag) Has(o PixelFormatDescriptorFlag) bool {
	return uint64(f)&uint64(o) > 0
}

// IsSingleFlag returns true if the value represents single flag value.
func (f PixelFormatDescriptorFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f PixelFormatDescriptorFlag) Format(s fmt.State, verb rune) {
	var nameMap map[PixelFormatDescriptorFlag]string
	switch verb {
	case 's':
		nameMap = pixelFormatDescriptorFlagNameMap
	case 'c':
		nameMap = pixelFormatDescriptorFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var pixelFormatDescriptorFlagNameMap = map[PixelFormatDescriptorFlag]string{
	PixelFormatDescriptorFlagBe:        "Be",
	PixelFormatDescriptorFlagPal:       "Pal",
	PixelFormatDescriptorFlagBitStream: "BitStream",
	PixelFormatDescriptorFlagHwAccel:   "HwAccel",
	PixelFormatDescriptorFlagPlanar:    "Planar",
	PixelFormatDescriptorFlagRgb:       "Rgb",
	PixelFormatDescriptorFlagAlpha:     "Alpha",
	PixelFormatDescriptorFlagBayer:     "Bayer",
	PixelFormatDescriptorFlagFloat:     "Float",
	PixelFormatDescriptorFlagXyz:       "Xyz",
}
var pixelFormatDescriptorFlagCgoNameMap = map[PixelFormatDescriptorFlag]string{
	PixelFormatDescriptorFlagBe:        "AV_PIX_FMT_FLAG_BE",
	PixelFormatDescriptorFlagPal:       "AV_PIX_FMT_FLAG_PAL",
	PixelFormatDescriptorFlagBitStream: "AV_PIX_FMT_FLAG_BITSTREAM",
	PixelFormatDescriptorFlagHwAccel:   "AV_PIX_FMT_FLAG_HWACCEL",
	PixelFormatDescriptorFlagPlanar:    "AV_PIX_FMT_FLAG_PLANAR",
	PixelFormatDescriptorFlagRgb:       "AV_PIX_FMT_FLAG_RGB",
	PixelFormatDescriptorFlagAlpha:     "AV_PIX_FMT_FLAG_ALPHA",
	PixelFormatDescriptorFlagBayer:     "AV_PIX_FMT_FLAG_BAYER",
	PixelFormatDescriptorFlagFloat:     "AV_PIX_FMT_FLAG_FLOAT",
	PixelFormatDescriptorFlagXyz:       "AV_PIX_FMT_FLAG_XYZ",
}
