// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new SeekFlag with the specified value set.
func (f SeekFlag) Add(o SeekFlag) SeekFlag { return SeekFlag(uint64(f) | uint64(o)) }

// Del returns a new SeekFlag with the specified value unset.
func (f SeekFlag) Del(o SeekFlag) SeekFlag { return SeekFlag(uint64(f) &^ uint64(o)) }

// Has returns true if value has the specific value set.
func (f SeekFlag) Has(o SeekFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f SeekFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f SeekFlag) Format(s fmt.State, verb rune) {
	var nameMap map[SeekFlag]string
	switch verb {
	case 's':
		nameMap = seekFlagNameMap
	case 'c':
		nameMap = seekFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var seekFlagNameMap = map[SeekFlag]string{
	SeekFlagAny:      "Any",
	SeekFlagBackward: "Backward",
	SeekFlagByte:     "Byte",
	SeekFlagFrame:    "Frame",
}
var seekFlagCgoNameMap = map[SeekFlag]string{
	SeekFlagAny:      "AVSEEK_FLAG_ANY",
	SeekFlagBackward: "AVSEEK_FLAG_BACKWARD",
	SeekFlagByte:     "AVSEEK_FLAG_BYTE",
	SeekFlagFrame:    "AVSEEK_FLAG_FRAME",
}
