// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new SoftwareScaleContextFlag with the specified value set.
func (f SoftwareScaleContextFlag) Add(o SoftwareScaleContextFlag) SoftwareScaleContextFlag {
	return SoftwareScaleContextFlag(uint64(f) | uint64(o))
}

// Del returns a new SoftwareScaleContextFlag with the specified value unset.
func (f SoftwareScaleContextFlag) Del(o SoftwareScaleContextFlag) SoftwareScaleContextFlag {
	return SoftwareScaleContextFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f SoftwareScaleContextFlag) Has(o SoftwareScaleContextFlag) bool {
	return uint64(f)&uint64(o) > 0
}

// IsSingleFlag returns true if the value represents single flag value.
func (f SoftwareScaleContextFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f SoftwareScaleContextFlag) Format(s fmt.State, verb rune) {
	var nameMap map[SoftwareScaleContextFlag]string
	switch verb {
	case 's':
		nameMap = softwareScaleContextFlagNameMap
	case 'c':
		nameMap = softwareScaleContextFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var softwareScaleContextFlagNameMap = map[SoftwareScaleContextFlag]string{
	SoftwareScaleContextFlagArea:         "Area",
	SoftwareScaleContextFlagBicubic:      "Bicubic",
	SoftwareScaleContextFlagBicublin:     "Bicublin",
	SoftwareScaleContextFlagBilinear:     "Bilinear",
	SoftwareScaleContextFlagFastBilinear: "FastBilinear",
	SoftwareScaleContextFlagGauss:        "Gauss",
	SoftwareScaleContextFlagLanczos:      "Lanczos",
	SoftwareScaleContextFlagPoint:        "Point",
	SoftwareScaleContextFlagSinc:         "Sinc",
	SoftwareScaleContextFlagSpline:       "Spline",
	SoftwareScaleContextFlagX:            "X",
}
var softwareScaleContextFlagCgoNameMap = map[SoftwareScaleContextFlag]string{
	SoftwareScaleContextFlagArea:         "SWS_AREA",
	SoftwareScaleContextFlagBicubic:      "SWS_BICUBIC",
	SoftwareScaleContextFlagBicublin:     "SWS_BICUBLIN",
	SoftwareScaleContextFlagBilinear:     "SWS_BILINEAR",
	SoftwareScaleContextFlagFastBilinear: "SWS_FAST_BILINEAR",
	SoftwareScaleContextFlagGauss:        "SWS_GAUSS",
	SoftwareScaleContextFlagLanczos:      "SWS_LANCZOS",
	SoftwareScaleContextFlagPoint:        "SWS_POINT",
	SoftwareScaleContextFlagSinc:         "SWS_SINC",
	SoftwareScaleContextFlagSpline:       "SWS_SPLINE",
	SoftwareScaleContextFlagX:            "SWS_X",
}
