// Code generated by enumflags.go. DO NOT EDIT.
package astiav

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new StreamEventFlag with the specified value set.
func (f StreamEventFlag) Add(o StreamEventFlag) StreamEventFlag {
	return StreamEventFlag(uint64(f) | uint64(o))
}

// Del returns a new StreamEventFlag with the specified value unset.
func (f StreamEventFlag) Del(o StreamEventFlag) StreamEventFlag {
	return StreamEventFlag(uint64(f) &^ uint64(o))
}

// Has returns true if value has the specific value set.
func (f StreamEventFlag) Has(o StreamEventFlag) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f StreamEventFlag) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f StreamEventFlag) Format(s fmt.State, verb rune) {
	var nameMap map[StreamEventFlag]string
	switch verb {
	case 's':
		nameMap = streamEventFlagNameMap
	case 'c':
		nameMap = streamEventFlagCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var streamEventFlagNameMap = map[StreamEventFlag]string{
	StreamEventFlagMetadataUpdated: "MetadataUpdated",
}
var streamEventFlagCgoNameMap = map[StreamEventFlag]string{
	StreamEventFlagMetadataUpdated: "AVSTREAM_EVENT_FLAG_METADATA_UPDATED",
}
