// Code generated by enumflags.go. DO NOT EDIT.
package demo

import "fmt"

func (f EnumType) Format(s fmt.State, verb rune) {
	var nameMap map[EnumType]string
	switch verb {
	case 's':
		nameMap = enumTypeNameMap
	case 'c':
		nameMap = enumTypeCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	fmt.Fprint(s, nameMap[f])
	if s.Flag('+') {
		fmt.Fprintf(s, "(%d)", int64(f))
	}
}

var enumTypeNameMap = map[EnumType]string{
	EnumTypeOne:   "One",
	EnumTypeTwo:   "Two",
	EnumTypeThree: "Three",
	EnumTypeFour:  "Four",
}
var enumTypeCgoNameMap = map[EnumType]string{
	EnumTypeOne:   "DEMO_ENUM_ONE",
	EnumTypeTwo:   "DEMO_ENUM_TWO",
	EnumTypeThree: "DEMO_ENUM_THREE",
	EnumTypeFour:  "DEMO_ENUM_FOUR",
}
