// Code generated by enumflags.go. DO NOT EDIT.
package demo

import "fmt"
import "math/bits"
import "maps"
import "slices"

// Del returns a new FlagType with the specified value set.
func (f FlagType) Add(o FlagType) FlagType { return FlagType(uint64(f) | uint64(o)) }

// Del returns a new FlagType with the specified value unset.
func (f FlagType) Del(o FlagType) FlagType { return FlagType(uint64(f) &^ uint64(o)) }

// Has returns true if value has the specific value set.
func (f FlagType) Has(o FlagType) bool { return uint64(f)&uint64(o) > 0 }

// IsSingleFlag returns true if the value represents single flag value.
func (f FlagType) IsSingleFlag() bool { return bits.OnesCount64(uint64(f)) == 1 }

func (f FlagType) Format(s fmt.State, verb rune) {
	var nameMap map[FlagType]string
	switch verb {
	case 's':
		nameMap = flagTypeNameMap
	case 'c':
		nameMap = flagTypeCgoNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	var started bool
	for _, k := range slices.Sorted(maps.Keys(nameMap)) {
		if !f.Has(k) {
			continue
		}
		if started {
			fmt.Fprint(s, "|")
		}
		started = true
		fmt.Fprint(s, nameMap[k])
		if s.Flag('+') {
			fmt.Fprintf(s, "(%d)", int64(k))
		}
	}
}

var flagTypeNameMap = map[FlagType]string{
	FlagTypeOne:   "One",
	FlagTypeTwo:   "Two",
	FlagTypeThree: "Three",
	FlagTypeFour:  "Four",
}
var flagTypeCgoNameMap = map[FlagType]string{
	FlagTypeOne:   "DEMO_FLAG_ONE",
	FlagTypeTwo:   "DEMO_FLAG_TWO",
	FlagTypeThree: "DEMO_FLAG_THREE",
	FlagTypeFour:  "DEMO_FLAG_FOUR",
}
