// Code generated by enumflags.go. DO NOT EDIT.
package demo

import "fmt"

func (f IotaType) Format(s fmt.State, verb rune) {
	var nameMap map[IotaType]string
	switch verb {
	case 's':
		nameMap = iotaTypeNameMap
	default:
		fmt.Fprintf(s, fmt.FormatString(s, verb), int64(f))
		return
	}
	fmt.Fprint(s, nameMap[f])
	if s.Flag('+') {
		fmt.Fprintf(s, "(%d)", int64(f))
	}
}

var iotaTypeNameMap = map[IotaType]string{
	IotaTypeOne:   "One",
	IotaTypeTwo:   "Two",
	IotaTypeThree: "Three",
	IotaTypeFour:  "Four",
}
